---
# tasks file for launch check logs every 30 seconds

- name: Create config file
  copy:
    src: files/watchlog
    dest: /etc/sysconfig/watchlog
  tags:
    - service_30

- name: Create log file
  copy:
    src: files/watchlog.log
    dest: /var/log/watchlog.log
  tags:
    - service_30

- name: Add script to find logs
  copy:
    src: files/watchlog.sh
    dest: /opt/watchlog.sh
    mode: u+x
  tags:
    - service_30

- name: Create unit for service
  copy:
    src: files/watchlog.service
    dest: /etc/systemd/system/watchlog.service
  tags:
    - service_30

- name: Create unit for timer
  copy:
    src: files/watchlog.timer
    dest: /etc/systemd/system/watchlog.timer
  notify:
    - start timer
    - start service
  tags:
    - service_30
